"""initial schema

Revision ID: b011541f1109
Revises: 
Create Date: 2026-01-26 00:55:46.312168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b011541f1109'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repo_display', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repo_ref_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repo_ref_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ended_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_activity_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('runner_header', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('runner_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('runner_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('directory', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('directory_has_git', sa.Boolean(), nullable=False),
    sa.Column('workdir_managed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('runner_session_id')
    )
    op.create_table('messages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('sessions')
    # ### end Alembic commands ###
